FROM maven:3.5.2-jdk-8-alpine

COPY ./target/java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar /java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar

CMD ["java -jar java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar"]
